### ISSUE TITLE
Staff Requests for Suppliers - questions

### ISSUE THREAD

**Issue by yegor256** [teamed/technoparkcorp.com#10]
_migrated from Trac, where originally posted by **l.kolosovska** on 8-Feb-2010 6:37pm_
1. Do "Days" show the delay in the staff allocation?
2. What is cost?
3. What is threshold?
4. How is response calculated?
5. Is it possible for me to suggest the candidates via thePanel?

**Comment by 0crat** [comment]
Job `gh:teamed/technoparkcorp.com#10` is not assigned, can't get performer
