### ISSUE TITLE
Penalties for the answer delay

### ISSUE THREAD

**Issue by yegor256** [teamed/technoparkcorp.com#15]
_migrated from Trac, where originally posted by **l.kolosovska** on 16-Feb-2010 4:11pm_

Implement the automatic detection of your answer delays in tickets.

If the delay in the ticket is bigger that 5 days, add 50% of the bonus for this supplier to the general PMO bonus.

**Comment by 0crat** [comment]
Job `gh:teamed/technoparkcorp.com#15` is not assigned, can't get performer
