### ISSUE TITLE
to integrate fazend TS into tickets

### ISSUE THREAD

**Issue by yegor256** [teamed/technoparkcorp.com#16]
_migrated from Trac, where originally posted by **yegor256** on 8-Apr-2010 4:51pm_

panel shall review all tickets, and find those that are assigned to PM. if a ticket is assigned to PM, than we should look who is the author of the last message. if it's architect we should review the content of the ticket. it should include:

```
reintegrate /branches/abc with /trunk
```

if this string is found, panel shall connect to TS, and push a script to reintegrator. the name of the script shall be: `project-reintegrate-branches-abc`. the script shall contain a full reintegration mechanism. only for PHP projects now.

if TS returns some integer - we just ignore the result. If it has some string, the panel posts this log into the ticket and reassigns the ticket back to the architect.

**Comment by 0crat** [comment]
Job `gh:teamed/technoparkcorp.com#16` is not assigned, can't get performer
