### ISSUE TITLE
Total values in Performance Reports

### ISSUE THREAD

**Issue by yegor256** [teamed/technoparkcorp.com#8]
_migrated from Trac, where originally posted by **l.kolosovska** on 8-Feb-2010 6:32pm_

That'll be great to add the total values concerning the period to [Performance Reports:http://beta.tpc2.com/p/PMO/Reports]:

Earned, Paid, Approved, Total Bonus

**Comment by 0crat** [comment]
Job `gh:teamed/technoparkcorp.com#8` is not assigned, can't get performer
